DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS personal;
CREATE TABLE usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    desde TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    contraseña TEXT NOT NULL,
    telefono INTEGER NOT NULL
);
CREATE TABLE personal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    desde TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    contraseña TEXT NOT NULL,
    telefono INTEGER NOT NULL
);